var url = location.href;
var index = url.indexOf('?');
var tn = url.slice(index + 1);

$(function(){
  var column1 = localStorage.getItem('column1+'+tn);
  var column2 = localStorage.getItem('column2+'+tn);
  var column3 = localStorage.getItem('column3+'+tn);
  var column4 = localStorage.getItem('column4+'+tn);
  var column5 = localStorage.getItem('column5+'+tn);
  var column1_class = localStorage.getItem('column1_class+'+tn);
  var column2_class = localStorage.getItem('column2_class+'+tn);
  var column3_class = localStorage.getItem('column3_class+'+tn);
  var column4_class = localStorage.getItem('column4_class+'+tn);
  var column5_class = localStorage.getItem('column5_class+'+tn);
  var column1_t = localStorage.getItem('column1_t+'+tn);
  var column2_t = localStorage.getItem('column2_t+'+tn);
  var column3_t = localStorage.getItem('column3_t+'+tn);
  var column4_t = localStorage.getItem('column4_t+'+tn);
  var column5_t = localStorage.getItem('column5_t+'+tn);
  var board_t = localStorage.getItem('board_t+'+tn);
  $('#column1').find('.column-c').html(column1);
  $('#column2').find('.column-c').html(column2);
  $('#column3').find('.column-c').html(column3);
  $('#column4').find('.column-c').html(column4);
  $('#column5').find('.column-c').html(column5);
  $('#column1').addClass(column1_class);
  $('#column2').addClass(column2_class);
  $('#column3').addClass(column3_class);
  $('#column4').addClass(column4_class);
  $('#column5').addClass(column5_class);
  $('#column1').find('.column-opt').find('.column-title').text(column1_t);
  $('#column2').find('.column-opt').find('.column-title').text(column2_t);
  $('#column3').find('.column-opt').find('.column-title').text(column3_t);
  $('#column4').find('.column-opt').find('.column-title').text(column4_t);
  $('#column5').find('.column-opt').find('.column-title').text(column5_t);
  $('.bord-title').text(board_t);
  $('title').text(board_t + ' / Kanban')
});

setInterval(function(){
  var column1 = $('#column1').find('.column-c').html();
  var column2 = $('#column2').find('.column-c').html();
  var column3 = $('#column3').find('.column-c').html();
  var column4 = $('#column4').find('.column-c').html();
  var column5 = $('#column5').find('.column-c').html();
  var column1_class = $('#column1').attr('class').replace('column','');
  var column2_class = $('#column2').attr('class').replace('column','');
  var column3_class = $('#column3').attr('class').replace('column','');
  var column4_class = $('#column4').attr('class').replace('column','');
  var column5_class = $('#column5').attr('class').replace('column','');
  var column1_t = $('#column1').find('.column-opt').find('.column-title').text();
  var column2_t = $('#column2').find('.column-opt').find('.column-title').text();
  var column3_t = $('#column3').find('.column-opt').find('.column-title').text();
  var column4_t = $('#column4').find('.column-opt').find('.column-title').text();
  var column5_t = $('#column5').find('.column-opt').find('.column-title').text();
  var board_t = $('.bord-title').text();
  localStorage.setItem('column1+'+tn, column1);
  localStorage.setItem('column2+'+tn, column2);
  localStorage.setItem('column3+'+tn, column3);
  localStorage.setItem('column4+'+tn, column4);
  localStorage.setItem('column5+'+tn, column5);
  localStorage.setItem('column1_t+'+tn, column1_t);
  localStorage.setItem('column2_t+'+tn, column2_t);
  localStorage.setItem('column3_t+'+tn, column3_t);
  localStorage.setItem('column4_t+'+tn, column4_t);
  localStorage.setItem('column5_t+'+tn, column5_t);
  localStorage.setItem('board_t+'+tn, board_t);
  localStorage.setItem('cardid+'+tn, cardid);
  localStorage.setItem('column1_class+'+tn, column1_class);
  localStorage.setItem('column2_class+'+tn, column2_class);
  localStorage.setItem('column3_class+'+tn, column3_class);
  localStorage.setItem('column4_class+'+tn, column4_class);
  localStorage.setItem('column5_class+'+tn, column5_class);
  localStorage.setItem('columnid+'+tn, columnidnum);
},1000);
